apiVersion: apps/v1
kind: Deployment
metadata:
  name: thesis-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thesis-backend
  template:
    metadata:
      labels:
        app: thesis-backend
    spec:
      containers:
        - name: thesis-backend
          image: thesis-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:mem:testdb
            - name: SPRING_DATASOURCE_DRIVERCLASSNAME
              value: org.h2.Driver
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.H2Dialect
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create-drop
            - name: SPRING_H2_CONSOLE_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: thesis-backend-service
spec:
  type: NodePort
  selector:
    app: thesis-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
