apiVersion: apps/v1
kind: Deployment
metadata:
  name: thesis-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thesis-backend
  template:
    metadata:
      labels:
        app: thesis-backend
    spec:
      containers:
        - name: thesis-backend
          image: thesis-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mariadb:3306/thesisdb
            - name: SPRING_DATASOURCE_USERNAME
              value: thesisuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: thesispass
---
apiVersion: v1
kind: Service
metadata:
  name: thesis-backend-service
spec:
  type: NodePort
  selector:
    app: thesis-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
