apiVersion: apps/v1
kind: Deployment
metadata:
  name: thesis-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thesis-backend
  template:
    metadata:
      labels:
        app: thesis-backend
    spec:
      containers:
      - name: thesis-backend
        image: thesis-backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: thesis-backend-service
spec:
  type: NodePort
  selector:
    app: thesis-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
