version: '3.8'

services:
  app:
    image: 'laravelsail/php80-composer:latest'
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'
    ports:
      - "8000:8000"
    # command: sh -c "rm -rf /var/www/html/laravel && composer create-project --prefer-dist laravel/laravel /var/www/html/laravel && cd laravel && php artisan serve --host=0.0.0.0 --port=8000"
    command: sh -c "[ ! -d /var/www/html/laravel ] && composer create-project --prefer-dist laravel/laravel /var/www/html/laravel; cd /var/www/html/laravel && php artisan serve --host=0.0.0.0 --port=8000 || php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - laravel_network

  db:
    image: mariadb
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
