apiVersion: apps/v1
kind: Deployment
metadata:
  name: thesis-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thesis-frontend
  template:
    metadata:
      labels:
        app: thesis-frontend
    spec:
      containers:
        - name: thesis-frontend
          image: thesis-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: thesis-frontend-service
spec:
  type: NodePort
  selector:
    app: thesis-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
