# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the executable JAR from the build context into the container
COPY build/libs/*.jar app.jar

# Expose the port the application runs on
EXPOSE 8180

# Run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]
