apiVersion: v1
kind: Service
metadata:
  name: thesis-prototype
spec:
  type: NodePort
  selector:
    app: thesis-prototype
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
